<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RollForward>Major</RollForward>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Authors>ChanSight Team</Authors>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
